// Idioma español para QuillTableBetter
export default {
  'col': 'Columna',
  'insColL': 'Insertar columna a la izquierda',
  'insColR': 'Insertar columna a la derecha',
  'delCol': 'Eliminar columna',
  'selCol': 'Seleccionar columna',
  'row': 'Fila',
  'headerRow': 'Fila de encabezado',
  'insRowAbv': 'Insertar fila arriba',
  'insRowBlw': 'Insertar fila abajo',
  'delRow': 'Eliminar fila',
  'selRow': 'Seleccionar fila',
  'mCells': 'Combinar celdas',
  'sCell': 'Dividir celda',
  'tblProps': 'Propiedades de tabla',
  'cellProps': 'Propiedades de celda',
  'insParaOTbl': 'Insertar párrafo fuera de la tabla',
  'insB4': 'Insertar antes',
  'insAft': 'Insertar después',
  'copyTable': 'Copiar tabla',
  'delTable': 'Eliminar tabla',
  'border': 'Borde',
  'color': 'Color',
  'width': 'Ancho',
  'background': 'Fondo',
  'dims': 'Dimensiones',
  'height': 'Alto',
  'padding': 'Relleno',
  'tblCellTxtAlm': 'Alineación del texto de celda',
  'alCellTxtL': 'Alinear texto de celda a la izquierda',
  'alCellTxtC': 'Centrar texto de celda',
  'alCellTxtR': 'Alinear texto de celda a la derecha',
  'jusfCellTxt': 'Justificar texto de celda',
  'alCellTxtT': 'Alinear texto de celda arriba',
  'alCellTxtM': 'Alinear texto de celda al centro',
  'alCellTxtB': 'Alinear texto de celda abajo',
  'dimsAlm': 'Dimensiones y alineación',
  'alTblL': 'Alinear tabla a la izquierda',
  'tblC': 'Centrar tabla',
  'alTblR': 'Alinear tabla a la derecha',
  'save': 'Guardar',
  'cancel': 'Cancelar',
  'colorMsg': 'El color no es válido. Prueba "#FF0000" o "rgb(255,0,0)" o "red".',
  'dimsMsg': 'El valor no es válido. Prueba "10px" o "2em" o "2%" o simplemente "2".',
  'colorPicker': 'Selector de color',
  'removeColor': 'Eliminar color',
  'black': 'Negro',
  'dimGrey': 'Gris oscuro',
  'grey': 'Gris',
  'lightGrey': 'Gris claro',
  'white': 'Blanco',
  'red': 'Rojo',
  'orange': 'Naranja',
  'yellow': 'Amarillo',
  'lightGreen': 'Verde claro',
  'green': 'Verde',
  'aquamarine': 'Aguamarina',
  'turquoise': 'Turquesa',
  'lightBlue': 'Azul claro',
  'blue': 'Azul',
  'purple': 'Púrpura'
};
